version: 1.0

instances:
  - name: carter
    type: robot
  - name: wp_home
    type: waypoint
  - name: wp_charge
    type: waypoint
  - name: wp_1
    type: waypoint
  - name: wp_2
    type: waypoint
  - name: wp_3
    type: waypoint
  - name: wp_4 
    type: waypoint
  - name: wp_5
    type: waypoint
  - name: wp_6
    type: waypoint
  - name: wp_7  
    type: waypoint
  - name: wp_8
    type: waypoint
  - name: wp_9
    type: waypoint
  - name: wp_10 
    type: waypoint
  - name: wp_11
    type: waypoint
  - name: wp_12 
    type: waypoint
  - name: wp_13 
    type: waypoint
  - name: wp_14 
    type: waypoint
  - name: wp_15
    type: waypoint
  - name: wp_16
    type: waypoint
  - name: wp_17
    type: waypoint
  - name: wp_18
    type: waypoint

predicates:
  - name: robot_at
    parameters: [carter, wp_home]
  - name: charging_point_at
    parameters: [wp_charge]
  - name: battery_low
    parameters: [carter]

connections:
  - [home, 1]
  - [home, charge]
  - [1, charge]
  - [1, 2]
  - [2, 3]
  - [3, 4]
  - [4, 1]
  - [1, 12]
  - [12, 5]
  - [12, 11]
  - [5, 6]
  - [6, 11]
  - [11, 10]
  - [10, 7]
  - [10, 9]
  - [7, 8]
  - [8, 9]
  - [9, 13]
  - [13, 15]
  - [15, 14]
  - [14, 16]
  - [16, 17]
  - [17, 18]
  - [18, 1]

goals:
  